apiVersion: v1
kind: Secret
metadata:
  name: audio-app-secrets
type: Opaque
stringData:
  database-url: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/audioeventapp"
  mongodb-url: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/audioeventapp?authSource=admin"
  redis-url: "redis://redis:6379/0"
  jwt-secret: "${JWT_SECRET}"
  postgres-user: "postgres"
  postgres-password: "${POSTGRES_PASSWORD}"
  mongodb-user: "mongodb"
  mongodb-password: "${MONGODB_PASSWORD}"
