apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-app-worker
  labels:
    app: audio-app
    tier: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audio-app
      tier: worker
  template:
    metadata:
      labels:
        app: audio-app
        tier: worker
    spec:
      containers:
      - name: worker
        image: ${DOCKER_REGISTRY}/audio-app-api:${IMAGE_TAG}
        imagePullPolicy: Always
        command: ["celery", "-A", "app.tasks.worker", "worker", "--loglevel=info"]
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: audio-app-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: audio-app-secrets
              key: jwt-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: audio-app-secrets
              key: redis-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: audio-app-secrets
              key: mongodb-url
        - name: ENV
          value: "production"
        - name: MODEL_PATH
          value: "/app/models/audio_event_detection_model.h5"
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
