apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: presence
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http
  type: ClusterIP
