apiVersion: v1
kind: Service
metadata:
  name: fingerprint-service-nodeport
  namespace: presence
  labels:
    app: fingerprint-service
spec:
  selector:
    app: fingerprint-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      name: http
  type: NodePort
