apiVersion: v1
kind: Service
metadata:
  name: fingerprint-service
  namespace: presence
  labels:
    app: fingerprint-service
spec:
  selector:
    app: fingerprint-service
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
