apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: presence
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 3005
      targetPort: 3005
      name: http
  type: ClusterIP
