apiVersion: v1
kind: Service
metadata:
  name: search-service-nodeport
  namespace: presence
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 30004
      name: http
  type: NodePort
