apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: presence
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 3003
      targetPort: 3003
      name: http
  type: ClusterIP
