apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-job
  namespace: presence
spec:
  template:
    spec:
      containers:
      - name: mongodb-init
        image: mongo:5
        command: ["/bin/sh", "-c"]
        args:
        - |
          until mongo --host mongodb --port 27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "print('Connected to MongoDB')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
          
          echo "MongoDB is ready, initializing data..."
          mongo --host mongodb --port 27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin presence /init/init.js
          echo "Initialization complete!"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mongodb-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mongodb-password
        volumeMounts:
        - name: init-script
          mountPath: /init
      volumes:
      - name: init-script
        configMap:
          name: mongodb-init
      restartPolicy: Never
  backoffLimit: 4
