apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: presence
data:
  init.js: |
    // Create contexts collection and add sample data
    db = db.getSiblingDB('presence');
    
    // Create contexts collection
    db.createCollection('contexts');
    
    // Create sample contexts
    db.contexts.insertMany([
      {
        name: "CNN Breaking News",
        type: "broadcast",
        usersCount: 1245,
        metadata: { channel: "CNN", topic: "News" },
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Taylor Swift Concert",
        type: "concert",
        usersCount: 5432,
        metadata: { artist: "Taylor Swift", venue: "Madison Square Garden" },
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Joe Rogan Podcast #1984",
        type: "podcast",
        usersCount: 876,
        metadata: { host: "Joe Rogan", guest: "Elon Musk" },
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]);
    
    // Create fingerprints collection
    db.createCollection('fingerprints');
    
    // Create usercontexts collection
    db.createCollection('usercontexts');
    
    // Create indexes
    db.contexts.createIndex({ createdAt: -1 });
    db.contexts.createIndex({ type: 1 });
    db.contexts.createIndex({ usersCount: -1 });
    
    db.usercontexts.createIndex({ userId: 1 });
    db.usercontexts.createIndex({ contextId: 1 });
    db.usercontexts.createIndex({ lastActiveAt: -1 });
    db.usercontexts.createIndex({ userId: 1, contextId: 1 }, { unique: true });
